### ISSUE TITLE
configuration / schedule changes apply only if meta is sdeleted

### ISSUE THREAD

**Issue by notcool6** [mitselek/Screenwerk-2016#14]
muudan confi, e confi all 1 scheduli vahetan teise vastu
playeri mängimise ajal ei kajastu muutused
playeri uuesti käivitamisel ei kajasutu muutused

võtan video playlistist välja
playeri mängimise ajal ei kajastu muutused
playeri uuesti käivitamisel?
ei lähe 

Meta kustutamisel muutb konf ja playlist

**Comment by mitselek** [comment]
Oled kindel, et muudatuste jõustamiseks ekraanigrupi ka publitseerisid?
