### ISSUE TITLE
DISPLAY_NUM under windows uses monitor number, not monitor location (maybe not issue but new function)

### ISSUE THREAD

**Issue by miikael** [mitselek/Screenwerk-2016#2]
Parameter "DISPLAY_NUM" under windows uses monitor number, not monitor location.
For example if the primary monitor is identifyed under windows as number 2 and the second monitor is identified number 1 and the "DISPLAY_NUM" parameter is set to "2", then the player starts on the primary monitor what windows identifies as 2.

**Comment by mitselek** [comment]
feature, not a bug
