### ISSUE TITLE
Video plays on the background

### ISSUE THREAD

**Issue by miikael** [mitselek/Screenwerk-2016#8]
When playlist starts playing from the start after 1st completion, there are some media that plays on the background. 
Found the bug when enabled sound on one video, so dont know exactly if only the video with the sound plays on the background or the whole playlist.
Also when disabled sound, then the bakcground video still played sound but the main playlist that was visable did not.

**Comment by mitselek** [comment]
fixed in b01787fdab462854ef58dc120eee6977a656a484
